### ISSUE TITLE
Missing git-lfs files

### ISSUE THREAD

**Issue by tuetschek** [ppapalampidi/SUMMER#1]
Hi,

thanks for an interesting paper! We'd like to try out your model for some experiments with theatre play generation, but when I cloned the repository, I got errors for the files stored in git-lfs:
```
Downloading dataset/train_TRIPOD_USE.pickle (839 MB)
Error downloading object: dataset/train_TRIPOD_USE.pickle (7618651): Smudge error: Error downloading dataset/train_TRIPOD_USE.pickle (76186512cd24509edb439d17e567ea949cc6117ea2a1389e3fae96efe2626a96): [76186512cd24509edb439d17e567ea949cc6117ea2a1389e3fae96efe2626a96] Object does not exist on the server: [404] Object does not exist on the server
```
(This is not just for this one file, the same error appears for other files in this directory.) Could you please try reuploading them or could you tell me how to build the pickle files? 

Thanks,
Ondrej

**Comment by ppapalampidi** [comment]
Hi Ondrej,

Thanks for your interest in our paper! I am so sorry for the error! I re-uploaded the large pickle files and I think that the error is now corrected. Could you try download them again and tell me if there still is a problem?

Best,
Pinelopi

**Comment by tuetschek** [comment]
Hi, 

I'm sorry for the delay, I was on holiday this week. 

Thank you very much, it seems to be working! I was able to checkout the files and start training. I'm just getting an error on one file -- is this supposed to happen?
```
Encountered 1 file(s) that should have been pointers, but weren't:
        dataset/labels_train_TRIPOD_silver.pickle
```

Best,
Ondrej

**Comment by tuetschek** [comment]
Hmm, actually maybe it matters? When I tried to run `python models/predict_labels.py`, I got this error:
```
Traceback (most recent call last):
  File "models/predict_labels.py", line 106, in <module>
    with open('../dataset/labels_train_silver.pickle', 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../dataset/labels_train_silver.pickle'
```

**Comment by ppapalampidi** [comment]
Hi again,

I think that it is now fixed. Let me know if you encounter more problems.

Best,
Pinelopi

**Comment by tuetschek** [comment]
Seems to be working now – thank you!

Best,
Ondrej
